# Generated by Django 5.0.4 on 2024-05-26 12:06

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id_salle', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('capacited', models.IntegerField(default=35)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id_filiere', models.AutoField(primary_key=True, serialize=False)),
                ('nom_filiere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id_module', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=150)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id_class_session', models.AutoField(primary_key=True, serialize=False)),
                ('heureDebut', models.TimeField(blank=True, null=True)),
                ('heureFin', models.TimeField(blank=True, null=True)),
                ('jour', models.CharField(max_length=50)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student_app.classroom')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.module')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleAssociate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assoc', models.DateField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.module')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('idStudent', models.AutoField(primary_key=True, serialize=False)),
                ('codeMassar', models.CharField(max_length=100, unique=True)),
                ('dateNaissance', models.DateField(null=True)),
                ('niveau', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.filiere')),
                ('student_groups', models.ManyToManyField(related_name='students', to='auth.group')),
                ('student_permissions', models.ManyToManyField(related_name='student_users', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            bases=('admin_app.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Marking',
            fields=[
                ('id_marking', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('date_marked', models.DateField(auto_now_add=True)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.classsession')),
                ('code_massar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student')),
            ],
        ),
    ]
