# Generated by Django 5.0.4 on 2024-05-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_student_filiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='jour',
            field=models.CharField(default='Lundi', max_length=50),
            preserve_default=False,
        ),
    ]
