# Generated by Django 5.0.4 on 2024-05-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_classsession_jour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dateNaissance',
            field=models.DateField(null=True),
        ),
    ]
